# Order to enqueue kernels in and what kernel config files to assign to each instance
Stages = [
	{name = 'scharr3_char', args = ['input', 'grad_xy']},
	{name = 'non_max_sup', args = ['grad_xy', 'grad_ang']},
	{name = 'edge_thinning', args = ['grad_ang', 'grad_ang']},
#	{name = 'gradient_debug', args = ['grad_ang', 'expanded'], range = {ref_arg = 'input'}},
	{name = 'link_edge_pixels', args = ['grad_ang', 'cont_data']},
#	{name = 'link_debug', args = ['cont_data', 'expanded'], range = {ref_arg = 'input'}},
	{name = 'find_segment_starts', args = ['grad_ang', 'cont_data', 'starts_cont']},
	{name = 'serial_reduce', args = ['starts_cont', 'start_coords'], range = {mode = 'EXACT', params = [1,1,1]}},
	{name = 'line_segments', args = ['starts_cont', 'start_coords', 'line_data', 'line_cnts']},#, range = {ref_arg = 'start_coords'}},
#	{name = 'colored_retrace_line', args = ['starts_cont', 'start_coords', 'line_data', 'line_cnts', 'retrace'], range = {ref_arg = 'start_coords'}},
#	{name = 'colored_retrace_starts', args = ['start_coords', 'retrace'], range = {ref_arg = 'start_coords'}},
	{name = 'arc_builder', args = ['start_coords', 'line_data', 'line_cnts', 'seg_in_arc', 'ellipse_foci'], range = {ref_arg = 'start_coords'}},
#	{name = 'foci_debug', args = ['line_data', 'seg_in_arc', 'ellipse_foci', 'retrace']},
#	{name = 'lost_seg_debug', args = ['retrace', 'starts_cont', 'retrace']},
	{name = 'serial_reduce_arc_seeds', args = ['seg_in_arc', 'arc_candidates'], range = {mode = 'EXACT', params = [1,1,1]}}
]

# hard-coded entries corresponding to program input
# this is a list of names that are to be associated with the hard-coded host inputs
# and are assumed to correspond to the first n entries of the ArgTracker where n is
# how many entries appear here.
# DO NOT MODIFY IF YOU AREN'T MODIFYING THE MAIN PROGRAM
HCInputArgs = [
'input',
]

# Master list of all kernel args by name used for OpenCL kernels listed in stages
# user configurable entries, instantiated as needed for specified stages
# Used for handling creation and checking of argument validity
[Args]
grad_xy = {type = 'image2d_t', channel_type = 'uint8', channel_count = 2}
grad_ang = {type = 'image2d_t', channel_type = 'int8', channel_count = 1}
cont_data = {type = 'image2d_t', channel_type = 'uint8', channel_count = 1}
starts_cont = {type = 'image2d_t', channel_type = 'uint8', channel_count = 1}#, size = {ref_arg = 'cont_data'}}
start_coords = {type = 'image1d_t', channel_type = 'int16', channel_count = 2, size = {mode = 'EXACT', params = [16384,1,1]}}
line_data = {type = 'image2d_t', channel_type = 'int8', channel_count = 2, size = {ref_arg = 'starts_cont'}}
line_cnts = {type = 'image1d_t', channel_type = 'uint16', channel_count = 1, size = {ref_arg = 'start_coords'}}
seg_in_arc = {type = 'image2d_t', channel_type = 'uint16', channel_count = 1, size = {ref_arg = 'starts_cont'}}
ellipse_foci = {type = 'image2d_t', channel_type = 'float', channel_count = 4, size = {ref_arg = 'starts_cont'}}
retrace = {type = 'image2d_t', channel_type = 'uint8', channel_count = 4, size = {ref_arg = 'input'}}
expanded = {type = 'image2d_t', channel_type = 'uint8', channel_count = 4, size = {mode = 'MULTIPLY', params = [3,3,1]}}
arc_candidates = {type = 'image1d_t', channel_type = 'int16', channel_count = 2, size = {mode = 'EXACT', params = [16384,1,1]}}