# Order to enqueue kernels in and what kernel config files to assign to each instance
Stages = [
	{name = 'scharr3_char', args = ['input', 'grad_xy']},
	{name = 'non_max_sup', args = ['grad_xy', 'grad_ang']},
	{name = 'edge_thinning', args = ['grad_ang', 'grad_ang']},
	{name = 'link_edge_pixels', args = ['grad_ang', 'cont_data']},
	{name = 'find_segment_starts', args = ['grad_ang', 'cont_data', 'starts_cont']},
	{name = 'serial_reduce', args = ['starts_cont', 'start_coords'], range = {mode = 'EXACT', params = [1,1,1]}},
#	{name = 'line_segments', args = ['starts_cont', 'start_coords', 'line_data', 'line_cnts']},#, range = {ref_arg = 'start_coords'}},
	{name = 'test_edge_injection', args =['start_coords', 'line_data', 'line_cnts'], range = {mode = 'EXACT', params = [1,1,1]}},
	{name = 'arc_builder', args = ['start_coords', 'line_data', 'line_cnts', 'arc_data', 'arc_dir_cnt', 'pre_solve_coeffs', 'ellipse_foci', 'ellipse_major'], range = {ref_arg = 'start_coords'}},
#	{name = 'serial_reduce_arcs', args = ['arc_dir_cnt', 'arc_coords'], range = {mode = 'EXACT', params = [1,1,1]}},
#	{name = 'arc_seg_adj_matrix', args = ['line_data', 'arc_data', 'arc_dir_cnt', 'arc_coords', 'ellipse_foci', 'ellipse_major', 'sparse_adj_matrix'], range = {ref_arg = 'arc_coords'}},
#	{name = 'arc_adj_simplify', args = ['sparse_adj_matrix', 'sparse_adj_matrix'], range = {ref_arg = 'arc_coords'}},
#	{name = 'arc_adj_consensus', args = ['arc_coords', 'pre_solve_coeffs', 'sparse_adj_matrix', 'ellipse_sol_abcd', 'ellipse_sol_e'], range = {ref_arg = 'arc_coords'}},

#### OUTPUT DEBUGGING KERNELS ####
#	{name = 'input_copy', args = ['input', 'retrace'], range = {ref_arg = 'input'}},
#	{name = 'arc_seg_adj_stripped', args = ['arc_data', 'arc_coords', 'retrace'], range = {ref_arg = 'retrace'}},
#	{name = 'gradient_debug', args = ['grad_ang', 'expanded'], range = {ref_arg = 'input'}},
#	{name = 'link_debug', args = ['cont_data', 'expanded'], range = {ref_arg = 'input'}},
	{name = 'fm_draw', args = ['arc_dir_cnt', 'ellipse_foci', 'ellipse_major', 'retrace'], range = {ref_arg = 'retrace'}},
#	{name = 'candys_theorem_example', args = ['line_data', 'arc_data', 'arc_dir_cnt', 'arc_coords', 'ellipse_foci', 'ellipse_major', 'retrace'], range = {mode = 'EXACT', params = [1,1,1]}},
#	{name = 'gen_ellipse_draw', args = ['ellipse_sol_abcd', 'ellipse_sol_e', 'retrace'], range = {ref_arg = 'arc_coords'}},
#	{name = 'conic_solve_debug', args = ['pre_solve_coeffs', 'retrace'], range = {ref_arg = 'retrace'}},	#DEPRECATED
#	{name = 'colored_retrace_line', args = ['starts_cont', 'start_coords', 'line_data', 'line_cnts', 'retrace'], range = {ref_arg = 'start_coords'}},
#	{name = 'colored_retrace_starts', args = ['start_coords', 'retrace'], range = {ref_arg = 'start_coords'}},
#	{name = 'foci_debug', args = ['line_data', 'arc_dir_cnt', 'ellipse_foci', 'retrace']},
#	{name = 'adj_debug', args = ['arc_coords', 'sparse_adj_matrix', 'retrace'], range = {ref_arg = 'arc_coords'}},
#	{name = 'adj_debug', args = ['arc_coords', 'undirected_sparse_adj_matrix', 'retrace'], range = {ref_arg = 'arc_coords'}},
#	{name = 'lost_seg_debug', args = ['retrace', 'starts_cont', 'retrace']},
]

# hard-coded entries corresponding to program input
# this is a list of names that are to be associated with the hard-coded host inputs
# and are assumed to correspond to the first n entries of the ArgTracker where n is
# how many entries appear here.
# DO NOT MODIFY IF YOU AREN'T MODIFYING THE MAIN PROGRAM
HCInputArgs = [
'input',
]

# Master list of all kernel args by name used for OpenCL kernels listed in stages
# user configurable entries, instantiated as needed for specified stages
# Used for handling creation and checking of argument validity
[Args]
grad_xy = {type = 'image2d_t', channel_type = 'uint8', channel_count = 2}
grad_ang = {type = 'image2d_t', channel_type = 'int8', channel_count = 1}
cont_data = {type = 'image2d_t', channel_type = 'uint8', channel_count = 1}
starts_cont = {type = 'image2d_t', channel_type = 'uint8', channel_count = 1}#, size = {ref_arg = 'cont_data'}}
start_coords = {type = 'image1d_t', channel_type = 'int16', channel_count = 2, size = {mode = 'EXACT', params = [16384,1,1]}}
line_data = {type = 'image2d_t', channel_type = 'int8', channel_count = 2, size = {ref_arg = 'starts_cont'}}
line_cnts = {type = 'image1d_t', channel_type = 'uint16', channel_count = 1, size = {ref_arg = 'start_coords'}}
arc_data = {type = 'image2d_t', channel_type = 'int32', channel_count = 2, size = {ref_arg = 'starts_cont'}}
arc_dir_cnt = {type = 'image2d_t', channel_type = 'int16', channel_count = 1, size = {ref_arg = 'starts_cont'}}
ellipse_foci = {type = 'image2d_t', channel_type = 'float', channel_count = 4, size = {ref_arg = 'starts_cont'}}
ellipse_major = {type = 'image2d_t', channel_type = 'float', channel_count = 1, size = {ref_arg = 'starts_cont'}}
pre_solve_coeffs = {type = 'image2d_t', channel_type = 'float', channel_count = 4, size = {mode = 'MULTIPLY', params = [2,2,1], ref_arg = 'starts_cont'}}
arc_coords = {type = 'image2d_t', channel_type = 'int16', channel_count = 2, size = {mode = 'EXACT', params = [16384,2,1]}}
sparse_adj_matrix = {type = 'image2d_t', channel_type = 'int32', channel_count = 4, size = {ref_arg = 'arc_coords'}}
undirected_sparse_adj_matrix = {type = 'image2d_t', channel_type = 'int32', channel_count = 4, size = {ref_arg = 'arc_coords'}}
ellipse_sol_abcd = {type = 'image2d_t', channel_type = 'float', channel_count = 4, size = {ref_arg = 'arc_coords'}}
ellipse_sol_e = {type = 'image2d_t', channel_type = 'float', channel_count = 1, size = {ref_arg = 'arc_coords'}}

#TODO: add a buffer for the non-arc-associated line segments and figure out how you want to handle those and arcs with 2 or 3 segments

#### PURELY DEGUGGING ONLY ARGS ####
retrace = {type = 'image2d_t', channel_type = 'uint8', channel_count = 4, size = {ref_arg = 'input'}}
expanded = {type = 'image2d_t', channel_type = 'uint8', channel_count = 4, size = {mode = 'MULTIPLY', params = [3,3,1]}}
